# Generated by Django 5.2.6 on 2025-09-13 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraumaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Patient', max_length=120)),
                ('triage_level', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green'), ('black', 'Black')], default='yellow', max_length=10)),
                ('triage_status', models.CharField(default='Pending Assessment', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_group', models.CharField(blank=True, default='', max_length=20)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('chief_complaint', models.CharField(blank=True, default='', max_length=50)),
                ('chief_complaint_other', models.CharField(blank=True, default='', max_length=200)),
                ('consciousness', models.CharField(blank=True, default='', max_length=50)),
                ('mechanism', models.CharField(blank=True, default='', max_length=50)),
                ('mechanism_other', models.CharField(blank=True, default='', max_length=200)),
                ('visible_injuries', models.BooleanField(default=False)),
                ('selected_injuries', models.JSONField(blank=True, default=list)),
                ('medical_alert', models.BooleanField(default=False)),
                ('allergies_history', models.BooleanField(default=False)),
                ('allergies_details', models.TextField(blank=True, default='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='triagex.traumasite')),
            ],
        ),
    ]
