# Generated by Django 5.2.6 on 2025-09-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='allergies_details',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='allergies_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='chief_complaint',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='chief_complaint_other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='consciousness',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mechanism',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mechanism_other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_alert',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='selected_injuries',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='visible_injuries',
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triagex.traumasite'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='triage_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='triage_status',
            field=models.CharField(max_length=50),
        ),
    ]
