# Generated by Django 5.2.6 on 2025-09-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagex', '0002_remove_patient_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_group',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='chief_complaint',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='chief_complaint_other',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='consciousness',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='mechanism',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='mechanism_other',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='selected_injuries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patient',
            name='visible_injuries',
            field=models.BooleanField(default=False),
        ),
    ]
