# Generated by Django 5.2.6 on 2025-09-14 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagex', '0003_patient_age_group_patient_allergies_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('bp_systolic', models.FloatField(blank=True, null=True)),
                ('bp_diastolic', models.FloatField(blank=True, null=True)),
                ('respiratory_rate', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='device', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='triagex.patient')),
            ],
        ),
    ]
