# Generated by Django 5.2.6 on 2025-09-14 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagex', '0004_vitalsign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamedicAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('source', models.CharField(default='trauma-site', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paramedic_actions', to='triagex.patient')),
            ],
        ),
    ]
