# Generated by Django 5.2.6 on 2025-09-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagex', '0005_paramedicaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age_group',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
